package com.flipkart.business;

import com.flipkart.bean.Payments;

/**
 * Interface for payment-related operations.
 * Provides methods for collecting and validating card details, requesting OTPs, and processing payments.
 *
 * @author Adarsh, Nitish
 */
public interface PaymentsService {

    /**
     * Validates the card details provided by the user.
     *
     * @param payments the Payments object containing card details to be validated
     * @return true if the card details are valid; false otherwise
     * @author Adarsh, Nitish
     */
    boolean validateCardDetails(Payments payments);

    /**
     * Generates a random OTP (One Time Password) for payment verification.
     *
     * @param payments the Payments object (used for passing payment details if needed)
     * @return the generated OTP
     * @author Adarsh, Nitish
     */
    int requestOTP(Payments payments);

    /**
     * Validates the provided OTP against the server-generated OTP.
     *
     * @param serverOTP the OTP generated by the server for verification
     * @return true if the entered OTP matches the server-generated OTP; false otherwise
     * @author Adarsh, Nitish
     */
    boolean validateOTP(int serverOTP);

    /**
     * Collects card details from the user.
     *
     * @return true if card details were collected successfully; false otherwise
     * @author Adarsh, Nitish
     */
    boolean collectCardDetails();

    boolean validateCardDetails();

    /**
     * Requests an OTP (One Time Password) for payment verification.
     *
     * @author Adarsh, Nitish
     */
    void requestOTP();

    /**
     * Processes the payment based on the collected and validated card details.
     *
     * @author Adarsh, Nitish
     */
    void processPayments();
}



//package com.flipkart.business;
//
//public interface PaymentsService {
//
//    boolean collectCardDetails();
//    boolean validateCardDetails();
//    void requestOTP();
//    public void processPayments();
//
//}
